puts "The Students of Villains Academy"
puts "------------------------------------"
puts "Dr Hannibal Lecter"
puts "Darth Vader"
puts "Nurse Ratched"
puts "Michael Corleone"
puts "Alex DeLarge"
puts "The Wicked Witch of the West"
puts "Terminator"
puts "Freddie Kruger"
puts "The joker"
puts "Jeffery Baratheon"
puts "Norman Bates"
# Finally we print the overall number of Students
print "Overall we have "
print 11
puts " great students"
